---
title: "stats-snack"
---

Stats Snack is a weekly meeting on Zoom for students and faculty at UMass Boston to discuss random topics, address questions, ask for advice, or attend/host workshops/talks related to statistics/anything data-related!

Fall 2025 regular meetings are **10am on Thursdays**!

See [here](https://docs.google.com/document/d/1U90DD1gmx9riJ2uYar72f_p2ifWZoKbu6zm7jRGefzI/edit?usp=sharing) for the weekly agenda. See [here](https://docs.google.com/spreadsheets/d/1THMtCrVZ_MdzZd65zggxyFiAo9cfHvp4rMyUUUuKoUg/edit?usp=sharing) for the Fall 2025 schedule.

**Here is the Zoom details:**\
Topic: Stats Snack Fall 2025 \
Time: Sep 11, 2025 10:00 AM Eastern Time (US and Canada) \
Every week on Thu, until Dec 4, 2025, 13 occurrence(s) \
Join Zoom Meeting <https://umassboston.zoom.us/j/98653141352>\
Meeting ID: 986 5314 1352

We are always looking for fun workshops and presentations. Also - it looks cool on a resume or CV to have a talk at a club about statistics 8) reach out to Candice (candice.koolhaas001\@umb.edu) if you have an idea for a topic or workshop, or if you have some fun educational links we can add to the website.

Stats Snack 2025-2026 is hosted by [Candice Koolhaas](https://candicekoolhaas.github.io/), a PhD student in the Developmental and Brain Sciences program.
