---
title: "Resources"
---

[This Google folder](https://drive.google.com/drive/folders/18txK5o41YNqf4dtX3CXQ-ZCkAz-GcfVY?usp=drive_link) contains any cool papers or other things we talk about at meetings!

Cool stats podcasts!\
[Quantitude](https://quantitudepod.org/), [Casual Inference](https://casualinfer.libsyn.com/), [Nullius in Verba](https://nulliusinverba.podbean.com/) (about science in general)

List of cool people doing interesting stuff regarding stats/experiment design\
[Richard McElreath](https://xcelab.net/rm/)\
[QuantPsych](https://simplistics.net/about-quantpsych/)\
[Daniel Lakens](https://sites.google.com/site/lakens2/) and his blog, the [20% Statistician](https://daniellakens.blogspot.com/)\
[Ben Bolker](https://ms.mcmaster.ca/~bolker/)\
[Judea Pearl](https://bayes.cs.ucla.edu/jp_home.html)\
[David Spiegelhalter](https://www.dpmms.cam.ac.uk/~ds28/) and his open access [stats course](https://www.statslab.cam.ac.uk/Dept/People/djsteaching/teaching17.html) with [video lectures](https://www.youtube.com/playlist?list=PLTBqohhFNBE9jRhvdtnuxj9FiOtDOnqoy)!\
[Mika Braginsky](https://mikabr.io/)

Book recommendations!\
[The Effect](https://theeffectbook.net/), [The Book of Why](https://www.amazon.com/Book-Why-Science-Cause-Effect/dp/046509760X), [Bayesian Workflow](https://arxiv.org/pdf/2011.01808), [Doing Bayesian Analysis](https://nyu-cdsc.github.io/learningr/assets/kruschke_bayesian_in_R.pdf), [The Art of Uncertainty](https://www.amazon.com/Art-Uncertainty-Navigate-Chance-Ignorance/dp/1324106115)

ASA, online courses, other educational materials!\
[ASA](https://www.amstat.org/) (student membership is only \$30 and you get access to free webinars and a magazine!)\
[The Carpentries](https://carpentries.org/lessons/) *free* lessons on computational skills!\
Great [free Python course](https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/) from MIT\
The [UMB Center for Statistical Computing](https://www.umb.edu/admissions/graduate-students/graduate-students-assistantships/center-for-statistical-computing/) hosts workshops and can be contacted for stats help!\
Jarrett's advanced stats course is a [bottomless pit of resources](https://biol609.github.io/schedule.html)!\
Recommended [IBM Python course](https://www.edx.org/learn/python/ibm-python-basics-for-data-science?index=product&queryId=2fd89abcbcdf0e50773df4d6a98b36c8&position=3)\
Joe Blitzstein's [famous stats 101 course](https://stat110.hsites.harvard.edu/) (lots of resources here too!)

Fun datasets:\
Chicago rat-hole dataset of [rats](https://rs.figshare.com/articles/dataset/Supplemental_Data_1_from_Rodent_indent_not_self-evident_a_case_of_mistaken_identity_of_the_Chicago_Rat_Hole_/30317790?backTo=%2Fcollections%2FSupplementary_material_from_Rodent_indent_not_self-evident_a_case_of_mistaken_identity_of_the_Chicago_Rat_Hole_%2F8079966&file=58599510)\
[Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/) (better than [irises](https://journal.r-project.org/articles/RJ-2022-020/RJ-2022-020.pdf)!)

Software-related:\
[sdmTMB package](https://pbs-assess.github.io/sdmTMB/) for patial and spatiotemporal GLMMs with TMB, [R-INLA](https://www.r-inla.org/) for Bayesian inference (and [inlabru](https://inlabru-org.github.io/inlabru/index.html) for more spatial modeling), [tidybayes](https://mjskay.github.io/tidybayes/) for visualizing and modeling Bayesian things\
Tutorial on [Shared Response Modeling](https://colab.research.google.com/drive/1vlVBE7s58yNgo921nPrnbIVpsbf89ocM?usp=sharing#scrollTo=HJ5hkPhXuN2-) (analysis method for pulling meaningful info from timeseries, EEG, fMRI, or eyetracking data)\
Tutorial on [using Github](https://happygitwithr.com/)!
